services:
  frontend:
    image: ecommerce-frontend:local
    container_name: ecommerce-frontend
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      - '${FRONTEND_PORT}:80'
    environment:
      PRODUCT_API_URL: '${PRODUCT_API_URL}'
      ORDER_API_URL: '${ORDER_API_URL}'
    restart: unless-stopped
